# Generated by Django 4.0.3 on 2022-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
