# Generated by Django 4.0.3 on 2022-03-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
