# Generated by Django 4.0.3 on 2022-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('fb', models.URLField(blank=True, null=True)),
                ('lin', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
                ('tw', models.URLField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Navbar setting',
            },
        ),
    ]
