# Generated by Django 4.0.3 on 2022-05-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_navbarsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsetting',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
