# Generated by Django 4.0.3 on 2022-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_seosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
