# Generated by Django 4.0.3 on 2022-05-05 10:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_seosettings_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(blank=True, max_length=500, null=True)),
                ('email_host', models.CharField(blank=True, max_length=500, null=True)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_use_tls', models.BooleanField(blank=True, null=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Email setting',
            },
        ),
    ]
