# Generated by Django 4.0.3 on 2022-05-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_emailsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsetting',
            name='email_backend',
        ),
    ]
