# Generated by Django 4.0.3 on 2022-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='QrCode/')),
            ],
        ),
    ]
