# Generated by Django 4.0.3 on 2022-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsetting',
            name='git',
            field=models.URLField(blank=True, null=True),
        ),
    ]
