# Generated by Django 4.0.3 on 2022-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_messages_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
