# Generated by Django 4.0.3 on 2022-05-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userdata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
