# Generated by Django 4.0.3 on 2022-05-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userdata_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='url',
        ),
        migrations.CreateModel(
            name='UserUrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userdata')),
            ],
        ),
    ]
