# Generated by Django 4.0.3 on 2022-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userdata_url_userurldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
