# Generated by Django 4.0.3 on 2022-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userdata_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
