# Generated by Django 4.0.3 on 2022-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userurldata_onlydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
