# Generated by Django 4.0.3 on 2022-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_userdata_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
