# Generated by Django 4.0.3 on 2022-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userdata_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='device_family',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
