# Generated by Django 4.0.3 on 2022-05-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_userdata_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='seen',
        ),
        migrations.CreateModel(
            name='UserDataSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userdata')),
            ],
        ),
    ]
