# Generated by Django 4.0.3 on 2022-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumeawards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('language_level', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Resume language',
            },
        ),
    ]
